### PR TITLE
Solved public relationship issue Swift 1.2

### PR DESCRIPTION
**Pull request by hardikdevios**
#295 Solved this issue

### CODE REVIEW

**Comment by anilreddi** [comment]
When will this be merged to swift12 branch?

**Comment by hardikdevios** [comment]
@anilreddi i don't know mate also i am not pretty much confident about the solution so might not sure about this , but i hope some expert find the solution soon because this is very Major bug and not allow us to build so lets hope for the best

**Comment by anilreddi** [comment]
Is this merged? I am still getting this error in 1.29

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!

**Pull request closed without merging**
