### PR TITLE
Swift 3 minor changes

### PR DESCRIPTION
**Pull request by hardikdevios**
Swift 3 - NSDate is now Date 3 `mogenrator.m`
Swift 3 - In One to Many Relationship methods making first argument optional `machine.swift.motemplate`

### CODE REVIEW

**Comment by hardikdevios** [comment]
Yes the reason is in your rake file you have Update the SDK and XCode but swift code is old in OSX. Do you want me to fix that issue as well Bro?

**Comment by rentzsch** [comment]
Ah, is that the issue? Yes please, you're in best position to figure out what's wrong and how to fix it.

**Comment by hardikdevios** [comment]
- `rake clean `
- `rake` 

I Think you are good to go with final `Swift 3`. Let me know for any other request Happy to help. 👍

**Comment by hardikdevios** [comment]
Cheers

**Comment by heumn** [comment]
Hey, I am just dropping by to say THANKS :)

congratulations-agree-136dgbul9Tk8Rq

**Pull request merged**
