### PR TITLE
Support swift 3.0

### PR DESCRIPTION
**Pull request by VladimirGoncharov**

### CODE REVIEW

**Comment by rentzsch** [comment]
Why are all the file modes changed?

**Comment by rentzsch** [comment]
Towards the final point: looks like 

https://github.com/rentzsch/mogenerator/blob/master/.travis.yml

`osx_image` probably needs to be upped from `xcode7.1` to `xcode8`

https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8

**Comment by VladimirGoncharov** [comment]
* Let's not change the mode of every file unless there's a compelling reason?

It is very strange, because I tried to replace the files form the original repository and it did not help.

* Why did Swift user info keys get removed?

I returned back to this logic

* We need to get Travis passing somehow. I'm not sure how to tell it this needs Swift 3 off the bat.

Unfortunately for the test that does not work :(

**Comment by rentzsch** [comment]
I moved the test along by specifying we need the 10.12 SDK, which is apparently required for Xcode 8 on Travis CI.

There's now a whole bunch of new Swift 3-related errors: <https://travis-ci.org/rentzsch/mogenerator/builds/162673879>

I don't put up with Swift shit, so someone else needs to fix this if mogenerator is ever to support Swift 3.

**Comment by rentzsch** [comment]
Sorry, didn't mean to close this PR.

**Comment by rentzsch** [comment]
Oops, forgot to mention I created a simplified commit of this branch / Pull Request on master. So work should proceed on current master.

**Comment by hardikdevios** [comment]
Well looks like you dont't like Swift anymore, Calling a "**Swift Shit**" is not a good sign bro.

**Comment by rentzsch** [comment]
Closing this since full Swift 3 landed in https://github.com/rentzsch/mogenerator/pull/349

**Pull request closed without merging**
