### PR TITLE
swift: fix incorrect override on class methods 

### LINKED ISSUE #253: Override Keyword Specified On Class Functions When Using Base Class Switch
When I pass in the --base-class switch to the command line arguments, the machine generated file uses override for the entityName() and entity(ManagedObjectContext) methods. Like so:

```
class _AssetMO: BaseManagedObject {
    // MARK: - Class methods

    override class func entityName () -> String {
        return "Asset"
    }

    override class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.entityName(), inManagedObjectContext: managedObjectContext);
    }
...
}
```
This same model when generated without the base class, does not emit the override keyword.
```
class _AssetMO: NSManagedObject {

    // MARK: - Class methods

    class func entityName () -> String {
        return "Asset"
    }

    class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.entityName(), inManagedObjectContext: managedObjectContext);
    }

...
}
```

The override causes a compiler error:
"Method does not override any method from its superclass"

My exact mogenerator command is:

```
/usr/local/bin/mogenerator --swift --base-class=BaseManagedObject -m ShareStuff.xcdatamodeld/ShareStuff.xcdatamodel  --output-dir ./ModelObjects
```

### PR DESCRIPTION
**Pull request by protocool**
These two class methods are synthesized by mogenerator, so they should only override when hasSuperentity, not when hasCustomSuperentity (which also returns true when a custom base class is specified). 

Fixes #253

### CODE REVIEW

**Comment by justin** [comment]
Can you target this towards `feature/swift12` instead of `master`? I'm going to do all the 1.29 stuff on that branch, so we can make sure all the Swift stuff is cool before merging it back in for a full release. Thanks!

**Comment by atomicbird** [comment]
It's not clear whether this is really what's needed-- though I'm not sure what would be better. As in the discussion on #253 the question of whether to use `override` depends on what's declared in the base class. Though mogenerator lets you specify a base class, it doesn't inspect that class.

**Comment by protocool** [comment]
Sorry, I've been flat out on work commitments.

The issue is that mogenerator generates entityName() and entity(managedObjectContext:) class methods. 

If you have a superentity (not a base class, an actual Core-Data superentity) then the subentities will also generate entityName and entity(managedObjectContext:) but swift demands that you mark those ones as 'override'

**Comment by atomicbird** [comment]
I was focusing on `--base-class` since the PR referenced #253, which was specifically about that.

The current `feature/swift12` branch doesn't incorporate this PR's change but I can't reproduce the problem. Using the model in this project at `test/test.xcdatamodel`, the `Human` entity (which is a superentity) gets this:

    public class func entityName () -> String {
        return "Human"
    }

    public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.entityName(), inManagedObjectContext: managedObjectContext);
    }

...while its child entity `Child` gets this:

    override public class func entityName () -> String {
        return "Child"
    }

    override public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
        return NSEntityDescription.entityForName(self.entityName(), inManagedObjectContext: managedObjectContext);
    }

This appears to be correct. The current template uses `hasCustomSuperentity`, so it doesn't incorporate this PR, but maybe the problem was elsewhere and got fixed somewhere in the meantime. If possible, could you check whether you can reproduce the problem with the latest `feature/swift12`?

**Comment by protocool** [comment]
Sorry. I submitted this a long time ago so details are hazy.

This PR fixes the spurious `override` added when you're using a custom base class. In #253 they work around it by specifying entityName() and entity(managedObjectContext:) in the custom base class, but IMO that's not appropriate: these are mogenerated methods and you should not be getting involved in their definition.

`hasCustomSuperEntity == YES` when you _either_ have a custom base class _or_ a superentity
`hasSuperEntity == YES` _only_ when you are the subentity of a core-data superentity

If you define a custom base class in your example, you're going to get a spurious `override` in Human entityName() and entity(managedObjectContext:).

Unfortunately I've had to switch to using a heavily modified private fork of mogenerator so I have no vested interest in getting it merged in. Feel free to close the PR if you don't think it adds value.

**Comment by atomicbird** [comment]
Thanks for being patient, I get it now. There's a potential problem that if the base class *does* implement those methods, suddenly the `override` is no longer spurious. But since the base class doesn't represent an actual entity, it seems reasonable to expect that they won't be present. I'll probably merge this once I work around another edge case it brings to light (inserting spurious `override`s in cases where the superentity doesn't have a custom class).

**Comment by dmdeller** [comment]
@atomicbird, the use case for having the methods defined in the base class is so that I can call them on an object declared as the base class.

For example, if my base class is `BaseRecord` and I have a method like:

    func doSomethingWithRecord(BaseRecord: record)
    {
        NSLog("Entity name: %@", record.entityName())
    }

This is a reasonable thing to want to do, because all of my entities have `entityName()`, as mogenerator generates it for them. But I can't call it unless it's defined in `BaseClass`, even if I always pass a subclass of `BaseClass` to `doSomethingWithRecord()`, not an instance of `BaseClass` itself.

This is probably always going to be somewhat ugly, because conceptually, `BaseClass` is an abstract class, which is a concept Swift doesn't have (AFAIK).

**Comment by atomicbird** [comment]
@dmdeller I see what you mean, but I can't see requiring base classes to include methods which by definition won't be used. The only way to get it right reliably is to know if the base class includes those methods and proceed accordingly. Short of that, Swift's rules mean that mogenerator needs to act based on what seems most likely. I'm betting it's that those methods won't be present.

**Comment by dmdeller** [comment]
Without `override` in the entities, Swift will not allow me to define those methods on my base class, which means I can no longer use them. That breaks my actual existing usage of mogenerator, which would be unfortunate. I can't speak for anyone else, so it's possible that my usage is unusual.

But I have to wonder why those methods even exist, if they are not meant to be used in that way. If you have an object `var person: Person`, would you ever need to call `person.entityName()`? Chances are, you already know the entity name in that case. The more likely reason you would need it is if you are working with an object that is declared as `var record: BaseRecord`. If this use case is no longer supported, why not simply remove these methods entirely?

Here's a thought: what if Swift automatically generated the base class (if configured), the way it does for entities? Assuming the base class is configured as `BaseRecord`, it could generate both a `BaseRecord` (iff it doesn't already exist) as well as a `_BaseRecord`, the latter of which would have definitions for `entityName()` and `entity()` that are then overridden. It may not be ideal, but at least it wouldn't break compilation and cause people to go searching for a workaround, as it does now.

**Comment by kballard** [comment]
@dmdeller The method exists because the entity name doesn't necessarily match the class name, so any code that creates entities needs to be able to ensure it gets the entity name correctly. Hard-coding the entity name in the creation code means that it's inflexible (you can't change the entity name in the model later).

I'm inclined to say that mogenerator should not be using `override` in this case, because *most* users of base classes will not have defined `entityName()` on the base. I could see it having a flag that says "assume base class has an entityName" method, thus re-adding the `override` flag, although that seems not particularly ideal.

Alternatively, there could just be a flag that tells mogenerator that the base class has a method with a given name, which the template could then use to determine if it needs the `override` flag (e.g. have a template-accessible method `superclassHasMethod("name")`). This would probably only need to be used with `entityName` but it would at least be a more general approach that would theoretically be more useful in the future if any more methods get added to generated classes.

**Comment by cpatterson** [comment]
@dmdeller If the base entity class does not implement those methods, but all of your leaf entity classes DO implement them, then isn't it appropriate to simply create a protocol called NameableEntity or something, and use THAT type as the parameter to your method instead? Like this:

```
fun doSomethingWithRecord(record:NameableEntity) 
{
     NSLog("Entity name: %@", record.entityName())
}
```

**Comment by atomicbird** [comment]
OK, what do people think about the following:

* By default with no `--base-class`, there's no `override` for these methods.
* If `--base-class` is used, behavior is same as the default for these methods, i.e. no `override` added.
* A new template var called something like `overrideBaseClass` would trigger adding `override` on these methods if `--base-class` is also used. You'd get the override by using something like `--base-class MyCustomBaseClass --template-var overrideBaseClass=true`

This way the default is not to require extra code in the base class but those who really want `entityName` and `entity` in their base classes can still get it.

I'm tempted to file a bug against Swift, because it seems increasingly dumb that we have to tell it whether we're overriding a method, but I guess that's a topic for somewhere else.

**Comment by kballard** [comment]
@atomicbird That sounds reasonable, though it has the drawback of requiring the `entity(_:)` method to also be implemented on the base class if it currently only implements `entityName()`.

> I'm tempted to file a bug against Swift, because it seems increasingly dumb that we have to tell it whether we're overriding a method, but I guess that's a topic for somewhere else.

I agree that this isn't the best place for a drawn-out discussion, but I just wanted to say that this is *only* an issue for code generators that are inheriting from other unknown classes. Beyond that one edge case, the `override` keyword is great because it avoids a very common source of error (accidentally overriding a superclass's method without realizing). And it throws an error if it's not actually overriding something to avoid a different easy error (of accidentally not overriding the method you thought you were). It's obviously a tradeoff, but one that has a good motivation. If you do want to file a radar, my suggestion would be to ask for some way to annotate a method as "possibly overriding" a superclass method, something expressly intended only for the use of code generators (perhaps a declaration modifier like `override(maybe)`).

**Comment by dmdeller** [comment]
That works for me, @atomicbird. I don't mind the drawback of needing to implement both, or neither. Thanks!

**Comment by atomicbird** [comment]
Delayed, but finally committed. This new behavior is in commit 78e62b1. I'm closing this pull request, but thanks @protocool for bringing it up.

**Pull request closed without merging**
