### PR TITLE
Support for protocols for Swift and Objective-C

### PR DESCRIPTION
**Pull request by webair**
I had the requirement to implement a protocol to the NSManagedObjects providing the method "entityName ". I thought it would be handsome if mogenerator could generate classes with a given protocol, so it would not be necessary to create an extra base class for only this purpose.

Also it would also be possible to create a default protocol for the mogenerator methods. What do you think?

### CODE REVIEW

**Comment by atomicbird** [comment]
If I understand this pull request correctly, it adds the `--protocol` option to optionally add a protocol reference in the machine code file, so that it looks something like

    class _ModuleName.EntityName: NSManagedObject,MyProtocolName {
    ....

That seems to work OK, but why not add the protocol to the human-editable subclass file instead? This pull request seems to work OK but I'm not sure I understand the need.

**Comment by webair** [comment]
Yes thats what it does. The idea is, to add a protocol to the generated managed object classes. For example the protocol:

    public protocol NamedManagedObject {
       static func entityName() -> String
    }

can now be added with the --protocol parameter:
    --protocol "NamedManagedObject"

Now i can use the protocol declaration instead of the custom base class, without touching any classes and neither have the need to add a base class. A thirdparty framework for example, can declare a protocol with the same naming as mogenerator and use it in its implementation. My assumption was, that this would give some more flexibility with the usage of mogenerator

I decided to add it to the machine file, so it can be changed frequently.

**Comment by anton-matosov** [comment]
You can do the same with simple class extension

```
public protocol NamedManagedObject {
    static func entityName() -> String
}

extension CoreData.NSManagedObject : NamedManagedObject {
    public static func entityName() -> String {
        ...
    }
}
```

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!

**Pull request closed without merging**
