### PR TITLE
issue 83, UTF8, and error checking

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
Friendly ping...

**Comment by rentzsch** [comment]
Sorry, I missed this. Thanks for the ping. Will try to look at it early next week.

**Comment by seanm** [comment]
Friendly re-ping... :)

**Comment by justin** [comment]
Sorry to be nitpicky, but this is a lot of different things. Is it possible you can break it out into separate PRs for the error handling issues you have, a separate one for UTF8, etc? Point it at `develop` as well if you don't mind. I promise ill look at it.

**Comment by justin** [comment]
We are declaring pull request and issue 0 now that 1.3 is out. If this is still an issue you'd like to see address with 1.30 and going forward, please open a new issue so we can start a fresh discussion. Thank you!

**Comment by seanm** [comment]
In my view, I already very carefully separated different things into different commits.  There's one commit for UTF8, one for the error handling, etc. I've looked, but don't see any way to make different github pull requests for different commits, it seems to be the whole thing or nothing.  Do you know a way?  Does github not allow you to cherry pick commits?

**Comment by rentzsch** [comment]
Hey Sean. I agree these would be better in separate Pull Requests. However, as a valued and long-suffering contributor I'll field these individual commits and see if and how they apply to a 1.30 base now.

**Comment by seanm** [comment]
Thanks. I'll be sure to make bite-sized pull requests in the future, but I'm still curious about how I'd fix things up now.  I'm no github expert, but all my googling suggests it's a PITA to go from where I am to what you want... ex:

http://stackoverflow.com/questions/16984169/github-how-to-submit-individual-pull-request-in-case-of-multiple-commits

I'd have a create a bunch of new branches, cherry pick, etc. or am I missing something?

github doesn't have a UI to just specify a commit SHA and merge it?!?!

**Comment by rentzsch** [comment]
Yeah I guess you'd need to create a branch for each Pull Request. Which does seem less granular than ideal.

**Comment by rentzsch** [comment]
OK I cherry-picked what applied cleanly to develop branch. If you want your type-attribute-is-just-a-warning and optional Mike Ash-style structs (which aren't even Mike Ash-style but normal NSObject classes now in 1.30) please issue a couple of new Pull Requests.

**Comment by rentzsch** [comment]
I think this can now be safely closed.

**Pull request closed without merging**
